// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMVK252Rlhr5F5bGRrhYO3DxTSC_XbYBs',
    appId: '1:300481321950:web:1e5ace775dc384ddd31b4f',
    messagingSenderId: '300481321950',
    projectId: 'hoost-6abdd',
    authDomain: 'hoost-6abdd.firebaseapp.com',
    storageBucket: 'hoost-6abdd.firebasestorage.app',
    measurementId: 'G-9K5DPEG84J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzvljqQ753dMJv08ot52kPz3R5ogQ9LBA',
    appId: '1:300481321950:android:a3e3de63d24c3c82d31b4f',
    messagingSenderId: '300481321950',
    projectId: 'hoost-6abdd',
    storageBucket: 'hoost-6abdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwMMpRgW1MTc6x-ZRSK-Mcs7Br-M7_ez8',
    appId: '1:300481321950:ios:f81916274481216bd31b4f',
    messagingSenderId: '300481321950',
    projectId: 'hoost-6abdd',
    storageBucket: 'hoost-6abdd.firebasestorage.app',
    iosBundleId: 'com.pottery.pottery',
  );
}
