/*import 'package:get/get.dart';




class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'Home': 'Home',
      'Search for pottery...': 'Search for pottery...',
      'Pottery App': 'Pottery App',
      'Notifications': 'Notifications',
      'Buy': 'Buy',
      'Settings': 'Settings',
      'Logout': 'Logout',
      'Menu': 'Menu',
      'Welcome to Pottery Shop': 'Welcome to Pottery Shop',
      'Select Language': 'Select Language',
      'English': 'English',
      'Kannada': 'Kannada',
      'Hindi': 'Hindi',
      'Tamil': 'Tamil',
      'Telugu': 'Telugu',
      'Clay Pot': 'Clay Pot',
      'Flower Pot': 'Flower Pot',
      'Color Pot': 'Color Pot',
      'Earthen Fine Pot': 'Earthen Fine Pot',
      'Water Pot': 'Water Pot',
      'Terracotta Pot': 'Terracotta Pot',
      'Herb Pot': 'Herb Pot',
      'Glazed Pot': 'Glazed Pot',
      'Cactus Pot': 'Cactus Pot',
      'Decorative Pot': 'Decorative Pot',
      'Succulent Pot': 'Succulent Pot',
      'Vintage Pot': 'Vintage Pot',

      'Notifications': 'Notifications',
      'New Product Arrival!': 'New Product Arrival!',
      'Check out our new pottery collection.': 'Check out our new pottery collection.',
      'New products.': 'New products.',
      'Hiking Pot': 'Hiking Pot',
      'Hiking Pot Details:': 'Hiking Pot Details:',
      '1. Lightweight and Compact: Made from lightweight materials like aluminum or titanium, making it easy to carry.':
      '1. Lightweight and Compact: Made from lightweight materials like aluminum or titanium, making it easy to carry.',
      '2. Durable and Heat-Resistant: Withstands high heat and rugged conditions for outdoor use.':
      '2. Durable and Heat-Resistant: Withstands high heat and rugged conditions for outdoor use.',
      '3. Efficient Heat Distribution: Conducts heat well, reducing fuel use.':
      '3. Efficient Heat Distribution: Conducts heat well, reducing fuel use.',
      '4. Multi-Functional Design: Includes features like foldable handles, strainer lids, and measurement markings.':
      '4. Multi-Functional Design: Includes features like foldable handles, strainer lids, and measurement markings.',
      '5. Easy to Clean: Often non-stick, making it convenient for minimal-waste camping.':
      '5. Easy to Clean: Often non-stick, making it convenient for minimal-waste camping.',

      'buy_pottery': 'Buy Pottery',
      'checkout': 'Checkout',
      'added_to_cart': 'added to your cart!',
      'removed_from_cart': 'removed from your cart!',
      'cart_empty': 'Your cart is empty!',
      'proceed_to_checkout': 'Proceed to Checkout',
      'items_in_cart': 'Items in Cart:',
      'place_order': 'Place Order',
      'order_placed': 'Order placed successfully!',
      'clay_pot': 'Clay Pot',
      'flower_pot': 'Flower Pot',
      'color_pot': 'Color Pot',
      'earthen_fine_pot': 'Earthen Fine Pot',
      'water_pot': 'Water Pot',
      'terracotta_pot': 'Terracotta Pot',
      'herb_pot': 'Herb Pot',
      'glazed_pot': 'Glazed Pot',
      'cactus_pot': 'Cactus Pot',
      'decorative_pot': 'Decorative Pot',
      'succulent_pot': 'Succulent Pot',
      'vintage_pot': 'Vintage Pot',


      'settings': 'Settings',
      'account_settings': 'Account Settings',
      'dark_mode': 'Dark Mode',
      'account_management': 'Account Management',
      'help_support': 'Help & Support',


      'account_management': 'Account Management',
      'manage_account_security': 'Manage your account security settings.',
      'change_password': 'Change Password',
      'enable_2fa': 'Enable 2-Factor Authentication',
      'enable_2fa_prompt': 'Would you like to enable 2FA?',
      'cancel': 'Cancel',
      'enable': 'Enable',
      'change_mobile_number': 'Change Mobile Number',
      'enter_new_mobile_number': 'Enter your new mobile number below:',
      'new_mobile_number': 'New Mobile Number',
      'mobile_number_changed': 'Mobile number changed successfully',
      'help_support': 'Help & Support',
      'welcome_help_support': 'Welcome to Help & Support!',
      'find_answers_help_support': 'Find answers to common questions or get in touch with support.',
      'help_articles': 'Help Articles',
      'contact_support': 'Contact Support',
      'support_numbers': 'You can contact support using the following numbers:\n1. 6379453853\n2. 9943790029',
      'opening_general_support': 'Opening general support details',
      'open_support_details': 'Open Support Details',
      'contacting_support': 'Contacting support',

      'account_settings': 'Account Settings',
      'manage_account_info': 'Manage your account settings here.',
      'update_account_info': 'Update Account Information',
      'new_account_info': 'New Account Info',
      'cancel': 'Cancel',
      'save': 'Save',

      'sellersPageTitle': 'Sellers Page',
      'manageProducts': 'Manage Products',
      'addNewPot': 'Add New Pot',
      'enterPotName': 'Enter Pot Name',
      'cancel': 'Cancel',
      'add': 'Add',
      'editProduct': 'Edit Product',
      'productDetails': 'Product Details',
      'save': 'Save',
      'addNewPotButton': 'Add New Pot',
      'Select Language': 'Select Language',


      'Account': 'Account',
      'Profile Information': 'Profile Information',
      'Full Name': 'Full Name',
      'Email': 'Email',
      'Business Information': 'Business Information',
      'Business Name': 'Business Name',
      'Business Contact': 'Business Contact',
      'Change Password': 'Change Password',
      'New Password': 'New Password',
      'Save Changes': 'Save Changes',
      'Success': 'Success',
      'Account details updated successfully.': 'Account details updated successfully.',


      'helpSupportTitle': 'Help & Support',
      'resetPassword': 'How to reset your password',
      'resetPasswordContent': 'To reset your password, go to the settings page and select "Change Password." Follow the steps to create a new password.',
      'enable2FA': 'How to enable 2FA',
      'enable2FAContent': 'To enable two-factor authentication, go to the security settings and enable 2FA. Follow the instructions provided to secure your account.',
      'contactSupport': 'How to contact support',
      'contactSupportContent': 'For support, you can reach out via the "Contact Us" form on our website or call our support helpline at 123-456-7890.',
      'FAQ': 'Frequently Asked Questions',
      'FAQContent': 'Here are answers to some commonly asked questions. You can also contact support for more details.',
      'termsConditions': 'Terms and Conditions',
      'termsConditionsContent': 'By using our service, you agree to abide by our terms and conditions. For more details, visit our website.',
      'privacyPolicy': 'Privacy Policy',
      'privacyPolicyContent': 'We value your privacy. Read our privacy policy to understand how we protect your data.',

      'clayPot': 'Clay Pot',
      'flowerPot': 'Flower Pot',
      'colorPot': 'Color Pot',
      'earthenPot': 'Earthen Pot',
      'waterPot': 'Water Pot',
      'terracottaPot': 'Terracotta Pot',
      'herbPot': 'Herb Pot',
      'glazedPot': 'Glazed Pot',
      'cactusPot': 'Cactus Pot',
      'decorativePot': 'Decorative Pot',
      'succulentPot': 'Succulent Pot',
      'vintagePot': 'Vintage Pot',
      'clayPotDetails': '1. Made from natural clay.\n2. Ideal for slow cooking.\n3. Eco-friendly.\n4. Retains heat and moisture.',
      'flowerPotDetails': '1. Decorative and versatile.\n2. Includes drainage options.\n3. Custom sizes.\n4. Lightweight and portable.',
      'colorPotDetails': '1. Vibrant and customizable.\n2. UV-resistant coatings.\n3. Variety of materials.\n4. Perfect for themed decor.',
      'earthenPotDetails': '1. Natural, rustic design.\n2. Keeps food cool.\n3. Durable and traditional.\n4. Eco-friendly.',
      'waterPotDetails': '1. Keeps water cool.\n2. Earthy taste.\n3. Eco-friendly option.\n4. Rustic design.',
      'terracottaPotDetails': '1. Breathable, natural material.\n2. Ideal drainage for plants.\n3. Rustic, unsealed finish.\n4. Great for outdoor use.',
      'herbPotDetails': '1. Compact for small herbs.\n2. Includes drainage holes.\n3. Suitable for balconies.\n4. Eco-friendly materials.',
      'glazedPotDetails': '1. Glossy, vibrant look.\n2. Non-absorbent surface.\n3. Easy to clean.\n4. Durable and decorative.',
      'cactusPotDetails': '1. Small, minimal-water use.\n2. Includes drainage.\n3. Modern design.\n4. Compact for shelves.',
      'decorativePotDetails': '1. Aesthetic, intricate designs.\n2. Multi-material options.\n3. Ideal decor or gift.\n4. Enhances any style.',
      'succulentPotDetails': '1. Compact, shallow design.\n2. Easy maintenance.\n3. Available in colors.\n4. Great for busy owners.',
      'vintagePotDetails': '1. Antique, rustic charm.\n2. Crafted from aged materials.\n3. Great for decor or collection.\n4. Fits classic themes.',

'Enable Dark Mode': 'Enable Dark Mode',
    },
    'kn_IN': {
      'Home': 'ಮೂಡು',
      'Search for pottery...': 'ಮಣ್ಣುಪೋಟಿ ಹುಡುಕಿ...',
      'Pottery App': 'ಮಣ್ಣಿನ ಉಪಕರಣ ಆಪ್',
      'Notifications': 'ನೋಟಿಫಿಕೇಶನ್ಗಳು',
      'Buy': 'ಕೊಂಡುಹಾಕು',
      'Settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್',
      'Logout': 'ಊರದಿಂದ ಹೊರಹೋಗಿ',
      'Menu': 'ಮೆನು',
      'Welcome to Pottery Shop': 'ಮಣ್ಣಿನ ಅಂಗಡಿಗೆ ಸ್ವಾಗತ',
      'Select Language': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
      'English': 'ಇಂಗ್ಲಿಷ್',
      'Kannada': 'ಕನ್ನಡ',
      'Hindi': 'ಹಿಂದಿ',
      'Tamil': 'ತಮಿಳು',
      'Telugu': 'ತೆಲುಗು',
      'Clay Pot': 'ಮಣ್ಣಿನ ಹಣ್ಣು',
      'Flower Pot': 'ಹೂವಿನ ಹಣ್ಣು',
      'Color Pot': 'ಬಣ್ಣ ಹಣ್ಣು',
      'Earthen Fine Pot': 'ಮಣ್ಣಿನ ಸೂಕ್ಷ್ಮ ಹಣ್ಣು',
      'Water Pot': 'ನೀರಿನ ಹಣ್ಣು',
      'Terracotta Pot': 'ಟೆರ್ರಕೋಟಾ ಹಣ್ಣು',
      'Herb Pot': 'ಹೆರಬ್ ಹಣ್ಣು',
      'Glazed Pot': 'ಗ್ಲೇಜ್ಡ್ ಹಣ್ಣು',
      'Cactus Pot': 'ಕ್ಯಾಕ್ಟಸ್ ಹಣ್ಣು',
      'Decorative Pot': 'ಆಲಂಕಾರಿಕ ಹಣ್ಣು',
      'Succulent Pot': 'ಸುಕೂಲಂಟು ಹಣ್ಣು',
      'Vintage Pot': 'ವಿಂಟೇಜ್ ಹಣ್ಣು',

      'Notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'New Product Arrival!': 'ಹೊಸ ಉತ್ಪನ್ನ ಪ್ರವೇಶ!',
      'Check out our new pottery collection.': 'ನಮ್ಮ ಹೊಸ ಮಣ್ಣು ವಸ್ತು ಸಂಗ್ರಹ ಪರಿಶೀಲಿಸಿ.',
      'New products.': 'ಹೊಸ ಉತ್ಪನ್ನಗಳು.',
      'Hiking Pot': 'ಹೈಕಿಂಗ್ ಪಾತ್ರೆ',
      'Hiking Pot Details:': 'ಹೈಕಿಂಗ್ ಪಾತ್ರೆ ವಿವರಗಳು:',
      '1. Lightweight and Compact: Made from lightweight materials like aluminum or titanium, making it easy to carry.':
      '1. ತೂಕ ಕಡಿಮೆ ಮತ್ತು ಚುಟುಕು: ಅಲ್ಯೂಮಿನಿಯಂ ಅಥವಾ ಟೈಟಾನಿಯಂನಂತಹ ತೂಕ ಕಡಿಮೆ ವಸ್ತುಗಳಿಂದ ತಯಾರಿಸಲಾಗಿದ್ದು, ಹೊರುವಿಕೆ ಸುಲಭವಾಗಿದೆ.',
      '2. Durable and Heat-Resistant: Withstands high heat and rugged conditions for outdoor use.':
      '2. ದೀರ್ಘಕಾಲಿಕ ಮತ್ತು ಶಾಖ ನಿರೋಧಕ: ಹೊರಾಂಗಣ ಬಳಕೆಗಾಗಿ ಹೆಚ್ಚು ತಾಪಮಾನ ಮತ್ತು ಕಠಿಣ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ತಡೆದುಕೊಳ್ಳುತ್ತದೆ.',
      '3. Efficient Heat Distribution: Conducts heat well, reducing fuel use.':
      '3. ಪರಿಣಾಮಕಾರಿ ತಾಪಮಾನ ವಿತರಣೆ: ತಾಪಮಾನವನ್ನು ಸಮರ್ಪಕವಾಗಿ ಹಂಚುತ್ತದೆ, ಇಂಧನ ಬಳಕೆಯನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.',
      '4. Multi-Functional Design: Includes features like foldable handles, strainer lids, and measurement markings.':
      '4. ಬಹು ಕಾರ್ಯಕ್ಷಮ ವಿನ್ಯಾಸ: ಮಡಚಬಹುದಾದ ಹ್ಯಾಂಡಲ್‌ಗಳು, ತೊಡಕು ದಪ್ಪೆಗಳು ಮತ್ತು ಮಾಪನ ಗುರುತುಗಳನ್ನು ಒಳಗೊಂಡಿದೆ.',
      '5. Easy to Clean: Often non-stick, making it convenient for minimal-waste camping.':
      '5. ಸ್ವಚ್ಛಗೊಳಿಸಲು ಸುಲಭ: ಅಂಟಿಕೊಳಿಸುವಿಕೆಯಿಲ್ಲ, ಕಡಿಮೆ ತ್ಯಾಜ್ಯ ಕ್ಯಾಂಪಿಂಗ್‌ಗೆ ಅನುಕೂಲ.',

      'buy_pottery': 'ಮಣ್ಣಿನ ಉತ್ಪನ್ನಗಳನ್ನು ಖರೀದಿಸಿ',
      'checkout': 'ಚೆಕ್ಔಟ್',
      'added_to_cart': 'ನಿಮ್ಮ ಚೀಲಕ್ಕೆ ಸೇರಿಸಲಾಗಿದೆ!',
      'removed_from_cart': 'ನಿಮ್ಮ ಚೀಲದಿಂದ ತೆಗೆದುಹಾಕಲಾಗಿದೆ!',
      'cart_empty': 'ನಿಮ್ಮ ಚೀಲ ಖಾಲಿಯಾಗಿದೆ!',
      'proceed_to_checkout': 'ಚೆಕ್ಔಟ್ ಗೆ ಮುಂದುವರೆಯಿರಿ',
      'items_in_cart': 'ಚೀಲದಲ್ಲಿರುವ ವಸ್ತುಗಳು:',
      'place_order': 'ಆರ್ಡರ್ ಹಾಕಿ',
      'order_placed': 'ಆರ್ಡರ್ ಯಶಸ್ವಿಯಾಗಿ ಹಾಕಲಾಗಿದೆ!',
      'clay_pot': 'ಮಣ್ಣಿನ ಕುಂಡ',
      'flower_pot': 'ಹೂವು ಕುಂಡ',
      'color_pot': 'ಬಣ್ಣದ ಕುಂಡ',
      'earthen_fine_pot': 'ಮಣ್ಣಿನ ನಾಜೂಕು ಕುಂಡ',
      'water_pot': 'ನೀರು ಕುಂಡ',
      'terracotta_pot': 'ಟೆರಾಕೋಟಾ ಕುಂಡ',
      'herb_pot': 'ಹerb ಕುಂಡ',
      'glazed_pot': 'ಗ್ಲೇಜ್ಡ್ ಕುಂಡ',
      'cactus_pot': 'ಕ್ಯಾಕ್ಟಸ್ ಕುಂಡ',
      'decorative_pot': 'ಶೃಂಗಾರಿಕ ಕುಂಡ',
      'succulent_pot': 'ಸುಕ್ಲೆಂಟ್ ಕುಂಡ',
      'vintage_pot': 'ಪ್ರಾಚೀನ ಕುಂಡ',


      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'account_settings': 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
      'account_management': 'ಖಾತೆ ನಿರ್ವಹಣೆ',
      'help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',


      'account_management': 'ಖಾತೆ ನಿರ್ವಹಣೆ',
      'manage_account_security': 'ನಿಮ್ಮ ಖಾತೆಯ ಭದ್ರತೆಯನ್ನು ನಿರ್ವಹಿಸಿ.',
      'change_password': 'ಪಾಸ್ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
      'enable_2fa': '2-ಫ್ಯಾಕ್ಟರ್ ಪ್ರಮಾಣೀಕರಣವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
      'enable_2fa_prompt': 'ನೀವು 2FA ಸಕ್ರಿಯಗೊಳಿಸಬೇಕೆ?',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'enable': 'ಸಕ್ರಿಯಗೊಳಿಸಿ',
      'change_mobile_number': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಬದಲಾಯಿಸಿ',
      'enter_new_mobile_number': 'ನಿಮ್ಮ ಹೊಸ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಕೆಳಗೆ ನಮೂದಿಸಿ:',
      'new_mobile_number': 'ಹೊಸ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'mobile_number_changed': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ',
      'help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
      'welcome_help_support': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲಕ್ಕೆ ಸ್ವಾಗತ!',
      'find_answers_help_support': 'ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ ಅಥವಾ ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ.',
      'help_articles': 'ಸಹಾಯ ಲೇಖನಗಳು',
      'contact_support': 'ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ',
      'support_numbers': 'ನೀವು ಈ ಕೆಳಗಿನ ಸಂಖ್ಯೆಗಳ ಮೂಲಕ ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಬಹುದು:\n1. 6379453853\n2. 9943790029',
      'opening_general_support': 'ಸಾಮಾನ್ಯ ಬೆಂಬಲ ವಿವರಗಳನ್ನು ತೆರೆಯುತ್ತಿದೆ',
      'open_support_details': 'ಬೆಂಬಲ ವಿವರಗಳನ್ನು ತೆರೆಯಿರಿ',
      'contacting_support': 'ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ',


      'account_settings': 'ಖಾತಾ ಸೆಟ್ಟಿಂಗ್ಗಳು',
      'manage_account_info': 'ಇಲ್ಲಿ ನಿಮ್ಮ ಖಾತಾ ಸೆಟ್ಟಿಂಗ್ಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
      'update_account_info': 'ಖಾತಾ ಮಾಹಿತಿಯನ್ನು ನವೀಕರಿಸಿ',
      'new_account_info': 'ಹೊಸ ಖಾತಾ ಮಾಹಿತಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'save': 'ಉಳಿತಾಯ',


      'sellersPageTitle': 'ಮಾರಾಟದವರ ಪೇಜ್',
      'manageProducts': 'ಉತ್ಪನ್ನಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
      'addNewPot': 'ಹೊಸ ಮಡಕೆ ಸೇರಿಸಿ',
      'enterPotName': 'ಮಡಕೆ ಹೆಸರು ನಮೂದಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'add': 'ಸೇರಿಸಿ',
      'editProduct': 'ಉತ್ಪನ್ನ ಸಂಪಾದಿಸಿ',
      'productDetails': 'ಉತ್ಪನ್ನ ವಿವರಗಳು',
      'save': 'ಉಳಿಸಿ',
      'addNewPotButton': 'ಹೊಸ ಮಡಕೆ ಸೇರಿಸಿ',
      'Select Language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',


      'Account': 'ಖಾತೆ',
      'Profile Information': 'ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿಗಳು',
      'Full Name': 'ಪೂರ್ಣ ಹೆಸರು',
      'Email': 'ಇಮೇಲ್',
      'Business Information': 'ವ್ಯಾಪಾರ ಮಾಹಿತಿ',
      'Business Name': 'ವ್ಯಾಪಾರ ಹೆಸರು',
      'Business Contact': 'ವ್ಯಾಪಾರ ಸಂಪರ್ಕ',
      'Change Password': 'ಪಾಸ್ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
      'New Password': 'ಹೊಸ ಪಾಸ್ವರ್ಡ್',
      'Save Changes': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
      'Success': 'ಯಶಸ್ಸು',
      'Account details updated successfully.': 'ಖಾತೆ ವಿವರಗಳು ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಡೇಟ್ ಆಗಿವೆ.',


      'helpSupportTitle': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
      'resetPassword': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಅನ್ನು ಹೇಗೆ ಮರುಹೊಂದಿಸಬೇಕು',
      'resetPasswordContent': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಲು, ಸೆಟ್ಟಿಂಗ್‌ಗಳಿಗೆ ಹೋಗಿ ಮತ್ತು "ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸು" ಆಯ್ಕೆಮಾಡಿ. ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಲು ಸೂಚನೆಗಳನ್ನು ಅನುಸರಿಸಿ.',
      'enable2FA': 'ಎಫ್‌ಎಎ ಅನ್ನು ಹೇಗೆ ಸಕ್ರಿಯಗೊಳಿಸಬೇಕು',
      'enable2FAContent': 'ಎಫ್‌ಎಎ (2-ಪರಿನಾಳೆ ದೃಢೀಕರಣ) ಅನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಲು, ಸುರಕ್ಷತಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳಿಗೆ ಹೋಗಿ ಮತ್ತು ಎಫ್‌ಎಎ ಅನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ. ಖಾತೆಯನ್ನು ಸುರಕ್ಷಿತಗೊಳಿಸಲು ಸೂಚನೆಗಳನ್ನು ಅನುಸರಿಸಿ.',
      'contactSupport': 'ಬೆಂಬಲವನ್ನು ಹೇಗೆ ಸಂಪರ್ಕಿಸಬೇಕು',
      'contactSupportContent': 'ಬೆಂಬಲಕ್ಕಾಗಿ, ನಮ್ಮ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ "ಸಂಪರ್ಕಿಸಿ" ಪೂರಕದ ಮೂಲಕ ಅಥವಾ ನಮ್ಮ ಬೆಂಬಲ ಹೆಲ್ಪ್‌ಲೈನ್‌ಗೆ ಕರೆ ಮಾಡಿ: 123-456-7890.',
      'FAQ': 'ಪ್ರಶ್ನೆ-ಉತ್ತರಗಳು',
      'FAQContent': 'ಇಲ್ಲಿ ಕೆಲ ಸಾಮಾನ್ಯವಾಗಿ ಕೇಳಲ್ಪಡುವ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಗಳಿವೆ. ಹೆಚ್ಚಿನ ಮಾಹಿತಿಗಾಗಿ ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಬಹುದು.',
      'termsConditions': 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
      'termsConditionsContent': 'ನಮ್ಮ ಸೇವೆಯನ್ನು ಬಳಸುವುದರ ಮೂಲಕ, ನೀವು ನಮ್ಮ ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ಪಾಲಿಸುತ್ತೀರಿ. ಹೆಚ್ಚಿನ ಮಾಹಿತಿಗಾಗಿ ನಮ್ಮ ವೆಬ್‌ಸೈಟ್ ಭೇಟಿ ನೀಡಿ.',
      'privacyPolicy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
      'privacyPolicyContent': 'ನಾವು ನಿಮ್ಮ ಗೌಪ್ಯತೆಯನ್ನು ಮಹತ್ವ ಕೊಡುತ್ತೇವೆ. ನಿಮ್ಮ ಡೇಟಾವನ್ನು ನಾವು ಹೇಗೆ ರಕ್ಷಿಸುತ್ತೇವೆ ಎಂಬುದನ್ನು ತಿಳಿದುಕೊಳ್ಳಲು ನಮ್ಮ ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ಓದಿ.',

      'clayPot': 'ಕಲೆ ಜಾರ್',
      'flowerPot': 'ಹೂವು ಕಡು',
      'colorPot': 'ರಂಗಿನ ಪಾತ್ರೆ',
      'earthenPot': 'ಮಣ್ಣಿನ ಪಾತ್ರೆ',
      'waterPot': 'ನೀರು ಜಾರ್',
      'terracottaPot': 'ಟೆರಕೋಟ್ಟಾ ಜಾರ್',
      'herbPot': 'ಹರ್ಬ್ ಜಾರ್',
      'glazedPot': 'ಚಿತ್ತಾರೆದ ಪಾತ್ರೆ',
      'cactusPot': 'ಕ್ಯಾಕ್ಟಸ್ ಜಾರ್',
      'decorativePot': 'ಅಲಂಕರಣಾತ್ಮಕ ಪಾತ್ರೆ',
      'succulentPot': 'ಸುಕುಲಂಟ್ ಜಾರ್',
      'vintagePot': 'ವಿಂಟೇಜ್ ಜಾರ್',
      'clayPotDetails': '1. ಸ್ವಾಭಾವಿಕ ಮಣ್ಣಿನಿಂದ ಮಾಡಲಾಗಿದೆ.\n2. ನಿಧಾನಗತಿಯ ಅಡುಗೆಗೆ ಸೂಕ್ತ.\n3. ಪರಿಸರ ಸ್ನೇಹಿ.\n4. ಹಿಟ್ ಮತ್ತು ತೇವವನ್ನು ಉಳಿಸುತ್ತದೆ.',
      'flowerPotDetails': '1. ಆಲಂಕಾರಿಕ ಮತ್ತು ವಿವಿಧ.\n2. ಹೊರಗಿನ ನೀರು ಸರಕು.\n3. ಕಸ್ಟಮ್ ಗಾತ್ರಗಳು.\n4. ಲಘು ಮತ್ತು ಸಾಗಿಸಲು ಸುಲಭ.',
      'colorPotDetails': '1. ಜೀವಂತ ಮತ್ತು ಕಸ್ಟಮೈಸ್ ಮಾಡಬಹುದಾದ.\n2. ಯೂವಿ-ರೆಸಿಸ್ಟೆಂಟ್ ಕವಚಗಳು.\n3. ವಿವಿಧ ಸಾಮಗ್ರಿಗಳು.\n4. ಥೀಮ್ ಡಿಕೋರಿಗೆ ಸರಿಹೊಂದುತ್ತದೆ.',
      'earthenPotDetails': '1. ಪ್ರಕೃತಿಯಿಂದ ಬಂದ ವಿನ್ಯಾಸ.\n2. ಆಹಾರವನ್ನು ಶೀತವಾಗಿಡುತ್ತದೆ.\n3. ದೃಢ ಮತ್ತು ಪ್ರಾಚೀನ.\n4. ಪರಿಸರ ಸ್ನೇಹಿ.',
      'waterPotDetails': '1. ನೀರನ್ನು ತಂಪಾಗಿಡುತ್ತದೆ.\n2. ಭೂಮಿಯ ರುಚಿ.\n3. ಪರಿಸರ ಸ್ನೇಹಿ ಆಯ್ಕೆ.\n4. ಪ್ರಕೃತಿಯ ವಿನ್ಯಾಸ.',
      'terracottaPotDetails': '1. ಉಸಿರಾಡುವ, ಪ್ರಕೃತಿ ಸಾಮಗ್ರಿ.\n2. ಸಸ್ಯಗಳಿಗೆ ಸೂಕ್ತವಾದ ನೀರಿನ ನಿಯಂತ್ರಣ.\n3. ಪ್ರಾಚೀನ ಹಾಗೂ ಅಸೀಕೃತವಾದ ಅಂತಿಮ finish.\n4. ಹೊರಗಿನ ಬಳಕೆಗೆ ಸೂಕ್ತ.',
      'herbPotDetails': '1. ಸಣ್ಣ ಗಿಡಗಳಿಗೆ ಅನುಕೂಲ.\n2. drainage ಹೊಳೆಗಳೊಂದಿಗೆ.\n3. ಬೆಂಗಳೂರ್‌ನಲ್ಲಿ ಅನುಕೂಲ.\n4. ಪರಿಸರ ಸ್ನೇಹಿ ಸಾಮಗ್ರಿಗಳು.',
      'glazedPotDetails': '1. ಬಟ್ಟೆ, ಜೀವನ್ತ ದೃಶ್ಯ.\n2. ಅಬ್ಸಾರ್ಬೆಂಟ್‌ ತತ್ವದಿಂದ.\n3. ಸ್ವಚ್ಛತೆ ಸುಲಭವಾಗಿದೆ.\n4. ಬಲವಾದ ಹಾಗೂ ಆಲಂಕಾರಿಕ.',
      'cactusPotDetails': '1. ಸಣ್ಣ, ಕಡಿಮೆ ನೀರಿನ ಬಳಕೆ.\n2. drainage ಅನ್ನು ಒಳಗೊಂಡಿದೆ.\n3. ನವೀನ ವಿನ್ಯಾಸ.\n4. ಶೆಲ್ಫ್ಗಳಿಗಾಗಿ ಸಣ್ಣ.',
      'decorativePotDetails': '1. ಸುಂದರ ವಿನ್ಯಾಸಗಳು.\n2. ಬಹು ಸಾಮಗ್ರಿ ಆಯ್ಕೆಗಳು.\n3. ಉಡುಗೊರೆಯಾದರೂ ಡಿಕೋರ್.\n4. ಎಲ್ಲಾ ಶೈಲಿಗಳಲ್ಲಿ ಅನುಕೂಲ.',
      'succulentPotDetails': '1. ಸುಲಭ ಜವಾಬ್ದಾರಿ.\n2. ವರ್ಣಗಳನ್ನು ಪ್ರಪ್ರತಿ.\n3. ಬಿಜಾರ ಬಗೆ ಹೇಗಿದೆ.\n4. ಜ್ಞಾನ ಹಿಡಿದಂತೆ',
      'vintagePotDetails': '1. ಪಾರಂಪರಿಕ ನೆಮ್ಮದಿ.\n2. ದೀರ್ಘ ಕಾಲ ನೆನೆಸಿದ ಕಾಲದ ಪ್ರಸ್ತುತ.\n3. ಮಾದರಿಯೊಂದಿಗೆ ಹೆಚ್ಚು ಸಂತೋಷ.\n4. ಸೆಲೆಕ್ಟ್, ಯಾವುದೇ.',

'Enable Dark Mode': 'ಡಾರ್ಕ್ ಮೋಡ್ ಅನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',

      'Dark Mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
    },
    'hi_IN': {
      'Home': 'मुख्य पृष्ठ',
      'Search for pottery...': 'मिट्टी के बर्तन खोजें...',
      'Pottery App': 'मिट्टी के बर्तन ऐप',
      'Notifications': 'सूचनाएँ',
      'Buy': 'खरीदें',
      'Settings': 'सेटिंग्स',
      'Logout': 'लॉग आउट',
      'Menu': 'मेनू',
      'Welcome to Pottery Shop': 'मिट्टी के बर्तन की दुकान में स्वागत है',
      'Select Language': 'भाषा चुनें',
      'English': 'अंग्रेजी',
      'Kannada': 'कन्नड़',
      'Hindi': 'हिंदी',
      'Tamil': 'तमिल',
      'Telugu': 'तेलुगु',
      'Clay Pot': 'मिट्टी का बर्तन',
      'Flower Pot': 'फूलों का बर्तन',
      'Color Pot': 'रंगीन बर्तन',
      'Earthen Fine Pot': 'मिट्टी का बारीक बर्तन',
      'Water Pot': 'पानी का बर्तन',
      'Terracotta Pot': 'टेराकोटा बर्तन',
      'Herb Pot': 'जड़ी-बूटी बर्तन',
      'Glazed Pot': 'चमचमाती बर्तन',
      'Cactus Pot': 'कैक्टस बर्तन',
      'Decorative Pot': 'सजावटी बर्तन',
      'Succulent Pot': 'सक्सुलेंट बर्तन',
      'Vintage Pot': 'विंटेज बर्तन',

      'Notifications': 'सूचनाएं',
      'New Product Arrival!': 'नया उत्पाद आगमन!',
      'Check out our new pottery collection.': 'हमारा नया मिट्टी के बर्तन संग्रह देखें।',
      'New products.': 'नये उत्पाद।',
      'Hiking Pot': 'हाइकिंग बर्तन',
      'Hiking Pot Details:': 'हाइकिंग बर्तन विवरण:',
      '1. Lightweight and Compact: Made from lightweight materials like aluminum or titanium, making it easy to carry.':
      '1. हल्का और कॉम्पैक्ट: हल्के एल्युमिनियम या टाइटेनियम जैसी सामग्री से बना, ले जाने में आसान।',
      '2. Durable and Heat-Resistant: Withstands high heat and rugged conditions for outdoor use.':
      '2. टिकाऊ और गर्मी प्रतिरोधी: बाहरी उपयोग के लिए उच्च तापमान और कठिन परिस्थितियों का सामना करता है।',
      '3. Efficient Heat Distribution: Conducts heat well, reducing fuel use.':
      '3. कुशल गर्मी वितरण: गर्मी को अच्छी तरह से वितरित करता है, ईंधन की खपत को कम करता है।',
      '4. Multi-Functional Design: Includes features like foldable handles, strainer lids, and measurement markings.':
      '4. बहु-कार्यात्मक डिज़ाइन: फोल्डेबल हैंडल, छन्ना ढक्कन और माप चिह्न जैसी सुविधाओं के साथ।',
      '5. Easy to Clean: Often non-stick, making it convenient for minimal-waste camping.':
      '5. साफ करने में आसान: नॉन-स्टिक, न्यूनतम कचरे के साथ कैंपिंग के लिए सुविधाजनक।',

      'buy_pottery': 'मिट्टी के बर्तन खरीदें',
      'checkout': 'चेकआउट',
      'added_to_cart': 'आपके कार्ट में जोड़ा गया!',
      'removed_from_cart': 'आपके कार्ट से हटाया गया!',
      'cart_empty': 'आपका कार्ट खाली है!',
      'proceed_to_checkout': 'चेकआउट के लिए आगे बढ़ें',
      'items_in_cart': 'कार्ट में वस्तुएँ:',
      'place_order': 'ऑर्डर करें',
      'order_placed': 'ऑर्डर सफलतापूर्वक किया गया!',
      'clay_pot': 'मिट्टी का बर्तन',
      'flower_pot': 'फूलों का बर्तन',
      'color_pot': 'रंगीन बर्तन',
      'earthen_fine_pot': 'मिट्टी का महीन बर्तन',
      'water_pot': 'पानी का बर्तन',
      'terracotta_pot': 'टेरेकोटा बर्तन',
      'herb_pot': 'जड़ी-बूटी का बर्तन',
      'glazed_pot': 'ग्लेज़ बर्तन',
      'cactus_pot': 'कैक्टस बर्तन',
      'decorative_pot': 'सजावटी बर्तन',
      'succulent_pot': 'सक्सेसिव बर्तन',
      'vintage_pot': 'प्राचीन बर्तन',

      'settings': 'सेटिंग्स',
      'account_settings': 'खाता सेटिंग्स',
      'dark_mode': 'डार्क मोड',
      'account_management': 'खाता प्रबंधन',
      'help_support': 'सहायता और समर्थन',


      'account_management': 'खाता प्रबंधन',
      'manage_account_security': 'अपने खाते की सुरक्षा सेटिंग्स प्रबंधित करें।',
      'change_password': 'पासवर्ड बदलें',
      'enable_2fa': '2-फैक्टर प्रमाणीकरण सक्षम करें',
      'enable_2fa_prompt': 'क्या आप 2FA सक्षम करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'enable': 'सक्षम करें',
      'change_mobile_number': 'मोबाइल नंबर बदलें',
      'enter_new_mobile_number': 'अपना नया मोबाइल नंबर नीचे दर्ज करें:',
      'new_mobile_number': 'नया मोबाइल नंबर',
      'mobile_number_changed': 'मोबाइल नंबर सफलतापूर्वक बदल दिया गया',
      'help_support': 'सहायता और समर्थन',
      'welcome_help_support': 'सहायता और समर्थन में आपका स्वागत है!',
      'find_answers_help_support': 'सामान्य प्रश्नों के उत्तर प्राप्त करें या समर्थन से संपर्क करें।',
      'help_articles': 'सहायता लेख',
      'contact_support': 'संपर्क समर्थन',
      'support_numbers': 'आप निम्नलिखित नंबरों के माध्यम से समर्थन से संपर्क कर सकते हैं:\n1. 6379453853\n2. 9943790029',
      'opening_general_support': 'सामान्य समर्थन विवरण खोलना',
      'open_support_details': 'सपोर्ट विवरण खोलें',
      'contacting_support': 'समर्थन से संपर्क किया जा रहा है',


      'account_settings': 'खाता सेटिंग्स',
      'manage_account_info': 'यहां अपने खाते की सेटिंग्स प्रबंधित करें।',
      'update_account_info': 'खाता जानकारी अपडेट करें',
      'new_account_info': 'नई खाता जानकारी',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',


      'sellersPageTitle': 'विक्रेता पृष्ठ',
      'manageProducts': 'उत्पाद प्रबंधन करें',
      'addNewPot': 'नया बर्तन जोड़ें',
      'enterPotName': 'बर्तन का नाम दर्ज करें',
      'cancel': 'रद्द करें',
      'add': 'जोड़ें',
      'editProduct': 'उत्पाद संपादित करें',
      'productDetails': 'उत्पाद विवरण',
      'save': 'सहेजें',
      'addNewPotButton': 'नया बर्तन जोड़ें',
      'Select Language': 'भाषा चुनें',


      'Account': 'खाता',
      'Profile Information': 'प्रोफ़ाइल जानकारी',
      'Full Name': 'पूरा नाम',
      'Email': 'ईमेल',
      'Business Information': 'व्यापार जानकारी',
      'Business Name': 'व्यापार का नाम',
      'Business Contact': 'व्यापार संपर्क',
      'Change Password': 'पासवर्ड बदलें',
      'New Password': 'नया पासवर्ड',
      'Save Changes': 'बदलाव सहेजें',
      'Success': 'सफलता',
      'Account details updated successfully.': 'खाता विवरण सफलतापूर्वक अपडेट किया गया।',



      'helpSupportTitle': 'सहायता और समर्थन',
      'resetPassword': 'आपका पासवर्ड कैसे रीसेट करें',
      'resetPasswordContent': 'पासवर्ड रीसेट करने के लिए, सेटिंग्स पेज पर जाएं और "पासवर्ड बदलें" चुनें। नया पासवर्ड बनाने के लिए दिए गए चरणों का पालन करें।',
      'enable2FA': '2FA को कैसे सक्षम करें',
      'enable2FAContent': 'टू-फैक्टर ऑथेंटिकेशन सक्षम करने के लिए, सुरक्षा सेटिंग्स में जाएं और 2FA को सक्रिय करें। अपने खाते को सुरक्षित करने के लिए दिए गए निर्देशों का पालन करें।',
      'contactSupport': 'समर्थन से कैसे संपर्क करें',
      'contactSupportContent': 'समर्थन के लिए, हमारी वेबसाइट पर "संपर्क करें" फॉर्म के माध्यम से संपर्क करें या हमारी हेल्पलाइन पर कॉल करें: 123-456-7890।',
      'FAQ': 'अक्सर पूछे जाने वाले प्रश्न',
      'FAQContent': 'यहाँ कुछ सामान्य प्रश्नों के उत्तर दिए गए हैं। अधिक जानकारी के लिए समर्थन से संपर्क कर सकते हैं।',
      'termsConditions': 'नियम और शर्तें',
      'termsConditionsContent': 'हमारी सेवा का उपयोग करके, आप हमारे नियमों और शर्तों का पालन करने के लिए सहमत हैं। अधिक जानकारी के लिए हमारी वेबसाइट देखें।',
      'privacyPolicy': 'गोपनीयता नीति',

      'privacyPolicyContent': 'हम आपकी गोपनीयता को महत्व देते हैं। यह जानने के लिए कि हम आपके डेटा की सुरक्षा कैसे करते हैं, हमारी गोपनीयता नीति पढ़ें।',

      'clayPot': 'क्ले पॉट',
      'flowerPot': 'फूलों का बर्तन',
      'colorPot': 'रंगीन बर्तन',
      'earthenPot': 'मिट्टी का बर्तन',
      'waterPot': 'पानी का बर्तन',
      'terracottaPot': 'टेरेकोटा बर्तन',
      'herbPot': 'हर्ब पॉट',
      'glazedPot': 'ग्लेज़ पॉट',
      'cactusPot': 'कैक्टस पॉट',
      'decorativePot': 'सजावटी बर्तन',
      'succulentPot': 'सुकुलेंट पॉट',
      'vintagePot': 'विंटेज पॉट',

      'clayPotDetails': '1. प्राकृतिक मिट्टी से बना।\n2. धीमी आंच पर पकाने के लिए आदर्श।\n3. पर्यावरण के अनुकूल।\n4. गर्मी और नमी को बनाए रखता है।',
      'flowerPotDetails': '1. सजावटी और बहुपरकारी।\n2. जल निकासी के विकल्प शामिल हैं।\n3. कस्टम आकार।\n4. हल्का और पोर्टेबल।',
      'colorPotDetails': '1. जीवंत और कस्टमाइज़ करने योग्य।\n2. यूवी-प्रतिरोधी कोटिंग्स।\n3. सामग्री की विविधता।\n4. थीम आधारित सजावट के लिए आदर्श।',
      'earthenPotDetails': '1. प्राकृतिक, देहाती डिज़ाइन।\n2. खाने को ठंडा रखता है।\n3. मजबूत और पारंपरिक।\n4. पर्यावरण के अनुकूल।',
      'waterPotDetails': '1. पानी को ठंडा रखता है।\n2. मिट्टी का स्वाद।\n3. पर्यावरण के अनुकूल विकल्प।\n4. देहाती डिज़ाइन।',
      'terracottaPotDetails': '1. श्वसन योग्य, प्राकृतिक सामग्री।\n2. पौधों के लिए आदर्श जल निकासी।\n3. देहाती, असंकीर्ण फिनिश।\n4. बाहरी उपयोग के लिए आदर्श।',
      'herbPotDetails': '1. छोटे हर्ब्स के लिए कॉम्पैक्ट।\n2. जल निकासी छेद शामिल हैं।\n3. बालकनी के लिए उपयुक्त।\n4. पर्यावरण के अनुकूल सामग्री।',
      'glazedPotDetails': '1. चमकदार, जीवंत रूप।\n2. अवशोषित न करने वाली सतह।\n3. साफ करने में आसान।\n4. मजबूत और सजावटी।',
      'cactusPotDetails': '1. छोटा, कम पानी का उपयोग।\n2. जल निकासी शामिल है।\n3. आधुनिक डिज़ाइन।\n4. शेल्फ के लिए कॉम्पैक्ट।',
      'decorativePotDetails': '1. सौंदर्यपूर्ण, जटिल डिज़ाइन।\n2. बहु-सामग्री विकल्प।\n3. आदर्श सजावट या उपहार।\n4. किसी भी शैली को बढ़ाता है।',
      'succulentPotDetails': '1. कॉम्पैक्ट, उथला डिज़ाइन।\n2. आसान रखरखाव।\n3. रंगों में उपलब्ध।\n4. व्यस्त मालिकों के लिए बेहतरीन।',
      'vintagePotDetails': '1. प्राचीन, देहाती आकर्षण।\n2. वृद्ध सामग्री से बना।\n3. सजावट या संग्रह के लिए बेहतरीन।\n4. क्लासिक विषयों में फिट बैठता है।',

      'Enable Dark Mode': 'डार्क मोड सक्षम करें',

      'Dark Mode': 'डार्क मोड',

    },
    'ta_IN': {
      'Home': 'வீடு',
      'Search for pottery...': 'குச்சி வெப்பக் கொள்கையைத் தேடுக...',
      'Pottery App': 'சமூக ஏவலுக்கான பலமையான ஆப்ஸ்',
      'Notifications': 'அறிவிப்புகள்',
      'Buy': 'வாங்கவும்',
      'Settings': 'அமைப்புகள்',
      'Logout': 'வெளியேறு',
      'Menu': 'மெனு',
      'Welcome to Pottery Shop': 'பொறி கவனம் தரும் வெட்டி நிலம்',
      'Select Language': 'மொழி தேர்வு செய்யவும்',
      'English': 'ஆங்கிலம்',
      'Kannada': 'கன்னடம்',
      'Hindi': 'இந்தி',
      'Tamil': 'தமிழ்',
      'Telugu': 'తెలుగు',
      'Clay Pot': 'மண் பானம்',
      'Flower Pot': 'மலர் பானம்',
      'Color Pot': 'நிற பானம்',
      'Earthen Fine Pot': 'மண் சிறந்த பானம்',
      'Water Pot': 'தண்ணீர் பானம்',
      'Terracotta Pot': 'பொருக்கப்பட்ட மண் பானம்',
      'Herb Pot': 'ஹெர்ப் பானம்',
      'Glazed Pot': 'பார்வை பானம்',
      'Cactus Pot': 'கேக்டஸ் பானம்',
      'Decorative Pot': 'அலங்கரிப்பு பானம்',
      'Succulent Pot': 'சுக்குலண்ட் பானம்',
      'Vintage Pot': 'வின்டேஜ் பானம்',

      'Notifications': 'அறிவிப்புகள்',
      'New Product Arrival!': 'புதிய தயாரிப்பு வந்துள்ளது!',
      'Check out our new pottery collection.': 'எங்களின் புதிய மண் பாத்திரங்களைக் காண்க.',
      'New products.': 'புதிய தயாரிப்புகள்.',
      'Hiking Pot': 'ஐக்கிங் பாத்திரம்',
      'Hiking Pot Details:': 'ஐக்கிங் பாத்திர விவரங்கள்:',
      '1. Lightweight and Compact: Made from lightweight materials like aluminum or titanium, making it easy to carry.':
      '1. இலகு மற்றும் குறுகிய அளவு: அலுமினியம் அல்லது டைட்டானியம் போன்ற இலகு பொருட்கள் மூலம் செய்யப்பட்டு, எடுத்துச் செல்ல எளிதாக உள்ளது.',
      '2. Durable and Heat-Resistant: Withstands high heat and rugged conditions for outdoor use.':
      '2. நீடித்த மற்றும் சூடு எதிர்ப்பும்: வெளிப்புற பயன்பாட்டிற்காக அதிக சூட்டையும் கடுமையான நிலைகளையும் தாங்குகிறது.',
      '3. Efficient Heat Distribution: Conducts heat well, reducing fuel use.':
      '3. சிறந்த வெப்ப பரவல்: வெப்பத்தை நன்றாக பரப்புகிறது, எரிபொருள் பயன்பாட்டை குறைக்கிறது.',
      '4. Multi-Functional Design: Includes features like foldable handles, strainer lids, and measurement markings.':
      '4. பல பயன்முறை வடிவமைப்பு: மடக்கக்கூடிய கைப்பிடிகள், வடிகட்டி தகடுகள் மற்றும் அளவீட்டு குறிக்கோள் ஆகியவற்றைக் கொண்டுள்ளது.',
      '5. Easy to Clean: Often non-stick, making it convenient for minimal-waste camping.':
      '5. சுத்தம் செய்ய எளிதானது: அதிகமாக ஒட்டாதது, குறைந்த கழிவு முகாமிடுவதற்காக எளிதானது.',


      'buy_pottery': 'களிமண் பானைகள் வாங்க',
      'checkout': 'சரிபார்ப்பு',
      'added_to_cart': 'உங்கள் கூடையில் சேர்க்கப்பட்டது!',
      'removed_from_cart': 'உங்கள் கூடையில் இருந்து அகற்றப்பட்டது!',
      'cart_empty': 'உங்கள் கூடை காலியாக உள்ளது!',
      'proceed_to_checkout': 'சரிபார்ப்புக்குச் செல்லவும்',
      'items_in_cart': 'கூடையில் உள்ள பொருட்கள்:',
      'place_order': 'ஆர்டர் செய்யவும்',
      'order_placed': 'ஆர்டர் வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
      'clay_pot': 'களிமண் பானை',
      'flower_pot': 'பூ பானை',
      'color_pot': 'நிற பானை',
      'earthen_fine_pot': 'மண்ணின fine பானை',
      'water_pot': 'தண்ணீர் பானை',
      'terracotta_pot': 'டெரகொட்டா பானை',
      'herb_pot': 'மருந்துப் பானை',
      'glazed_pot': 'கிளேஸ் பானை',
      'cactus_pot': 'காக்டஸ் பானை',
      'decorative_pot': 'அலங்கார பானை',
      'succulent_pot': 'சக்யூலண்ட் பானை',
      'vintage_pot': 'விண்டேஜ் பானை',

      'settings': 'அமைப்புகள்',
      'account_settings': 'கணக்கு அமைப்புகள்',
      'dark_mode': 'இருண்ட இயக்கம்',
      'account_management': 'கணக்கு மேலாண்மை',
      'help_support': 'உதவி மற்றும் ஆதரவு',


      'account_management': 'கணக்கு மேலாண்மை',
      'manage_account_security': 'உங்கள் கணக்கின் பாதுகாப்பு அமைப்புகளை மேலாண்மை செய்யவும்.',
      'change_password': 'கடவுச்சொல் மாற்றவும்',
      'enable_2fa': '2-பரிமாண அங்கீகாரம் செயல்படுத்தவும்',
      'enable_2fa_prompt': 'நீங்கள் 2FA ஐ செயல்படுத்த விரும்புகிறீர்களா?',
      'cancel': 'ரத்து செய்யவும்',
      'enable': 'செயல்படுத்தவும்',
      'change_mobile_number': 'மொபைல் எண்ணை மாற்றவும்',
      'enter_new_mobile_number': 'உங்கள் புதிய மொபைல் எண்ணை கீழே உள்ளீடு செய்யவும்:',
      'new_mobile_number': 'புதிய மொபைல் எண்',
      'mobile_number_changed': 'மொபைல் எண் வெற்றிகரமாக மாற்றப்பட்டது',
      'help_support': 'உதவி மற்றும் ஆதரவு',
      'welcome_help_support': 'உதவி மற்றும் ஆதரவுக்கு வரவேற்கின்றேன்!',
      'find_answers_help_support': 'பொதுவான கேள்விகளுக்கு பதில்களை கண்டுபிடிக்கவும் அல்லது ஆதரவுடன் தொடர்பு கொள்ளவும்.',
      'help_articles': 'உதவி கட்டுரைகள்',
      'contact_support': 'ஆதரவை தொடர்பு கொள்ளவும்',
      'support_numbers': 'நீங்கள் கீழ்காணும் எண்களுடன் ஆதரவை தொடர்பு கொள்ளலாம்:\n1. 6379453853\n2. 9943790029',
      'opening_general_support': 'பொதுவான ஆதரவு விவரங்களை திறக்க',
      'open_support_details': 'ஆதரவு விவரங்களை திறக்கவும்',
      'contacting_support': 'ஆதரவை தொடர்பு கொண்டுள்ளேன்',


      'account_settings': 'கணக்கு அமைப்புகள்',
      'manage_account_info': 'இங்கே உங்கள் கணக்கு அமைப்புகளை மேலாண்மை செய்யவும்.',
      'update_account_info': 'கணக்கு தகவலை புதுப்பிக்கவும்',
      'new_account_info': 'புதிய கணக்கு தகவல்',
      'cancel': 'ரத்து செய்யவும்',
      'save': 'சேமிக்கவும்',

      'sellersPageTitle': 'விற்பனையாளர் பக்கம்',
      'manageProducts': 'தயாரிப்புகளை நிர்வகிக்கவும்',
      'addNewPot': 'புதிய கூடு சேர்க்கவும்',
      'enterPotName': 'கூடின் பெயரை உள்ளிடவும்',
      'cancel': 'ரத்து செய்',
      'add': 'சேர்க்கவும்',
      'editProduct': 'தயாரிப்பு திருத்தம்',
      'productDetails': 'தயாரிப்பு விவரங்கள்',
      'save': 'சேமிக்கவும்',
      'addNewPotButton': 'புதிய கூடு சேர்க்கவும்',
      'Select Language': 'மொழியைத் தேர்ந்தெடுக்கவும்',


      'Account': 'கணக்கு',
      'Profile Information': 'சுயவிவரத் தகவல்',
      'Full Name': 'முழு பெயர்',
      'Email': 'மின்னஞ்சல்',
      'Business Information': 'வணிகத் தகவல்',
      'Business Name': 'வணிகப் பெயர்',
      'Business Contact': 'வணிகத் தொடர்பு',
      'Change Password': 'பாஸ்வேர்டை மாற்று',
      'New Password': 'புதிய பாஸ்வேர்ட்',
      'Save Changes': 'மாற்றங்களை சேமிக்கவும்',
      'Success': 'வெற்றி',
      'Account details updated successfully.': 'கணக்கு விவரங்கள் வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',

      'helpSupportTitle': 'உதவி மற்றும் ஆதரவு',
      'resetPassword': 'உங்கள் கடவுச்சொல்லை மீட்டமைக்க எப்படி',
      'resetPasswordContent': 'கடவுச்சொல்லை மீட்டமைக்க, அமைப்புகள் பக்கத்திற்கு செல்லவும் மற்றும் "கடவுச்சொல்லை மாற்றவும்" தேர்வு செய்யவும். புதிய கடவுச்சொல்லை உருவாக்குவதற்கான வழிமுறைகளைப் பின்பற்றவும்.',
      'enable2FA': '2FA-ஐ எவ்வாறு இயக்குவது',
      'enable2FAContent': 'இரட்டை காரணி சரிபார்ப்பை இயக்க, பாதுகாப்பு அமைப்புகளுக்கு சென்று 2FA-ஐ இயக்கவும். உங்கள் கணக்கை பாதுகாப்பதற்கான வழிமுறைகளைப் பின்பற்றவும்.',
      'contactSupport': 'ஆதரவை எவ்வாறு தொடர்புகொள்வது',
      'contactSupportContent': 'ஆதரவு பெற, எங்கள் இணையதளத்தில் உள்ள "தொடர்பு கொள்ள" படிவத்தின் மூலமாக அணுகவும் அல்லது எங்கள் ஹெல்ப்லைனுக்கு அழைக்கவும்: 123-456-7890.',
      'FAQ': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'FAQContent': 'இங்கே சில பொதுவான கேள்விகளுக்கு பதில்கள் உள்ளன. மேலும் விவரங்களுக்கு ஆதரவை தொடர்பு கொள்ளவும்.',
      'termsConditions': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      'termsConditionsContent': 'எங்கள் சேவையைப் பயன்படுத்துவதன் மூலம், நீங்கள் எங்கள் விதிமுறைகள் மற்றும் நிபந்தனைகளைப் பின்பற்ற ஒப்புக்கொள்கிறீர்கள். மேலும் விவரங்களுக்கு எங்கள் இணையதளத்தைப் பார்க்கவும்.',
      'privacyPolicy': 'தனியுரிமை கொள்கை',
      'privacyPolicyContent': 'நாங்கள் உங்கள் தனியுரிமையை மதிக்கிறோம். எங்கள் தனியுரிமைக் கொள்கையைப் படிக்கவும்.',

      'clayPot': 'மண்ணுக்குப் பானை',
      'flowerPot': 'பூப்பாட்டி',
      'colorPot': 'நிறப் பானை',
      'earthenPot': 'மண் பானை',
      'waterPot': 'நீர் பானை',
      'terracottaPot': 'டெரிகோட்டா பானை',
      'herbPot': 'புஷ்ப பானை',
      'glazedPot': 'கிளாஸ் பானை',
      'cactusPot': 'காக்டஸ் பானை',
      'decorativePot': 'அலங்கார பானை',
      'succulentPot': 'சகுலென்ட் பானை',
      'vintagePot': 'பழமையான பானை',

      'clayPotDetails': '1. இயற்கை மண்ணிலிருந்து தயாரிக்கப்பட்டது.\n2. மிதமான வெப்பத்தில் சமைப்பதற்கு உகந்தது.\n3. சுற்றுச்சூழலுக்கு இடர்பாடு இல்லாதது.\n4. வெப்பம் மற்றும் ஈரப்பதத்தை பராமரிக்கிறது.',
      'flowerPotDetails': '1. அலங்கார மற்றும் பல்வேறு பயன்பாடுகளுடன்.\n2. வடிகட்டி விருப்பங்களைக் கொண்டுள்ளது.\n3. தனிப்பயன் அளவுகள்.\n4. எளிமையான மற்றும் கொண்டு செல்லத்தக்கது.',
      'colorPotDetails': '1. வேதியியல் மற்றும் தனிப்பயன் செய்யக்கூடியது.\n2. யூ.வி. எதிர்ப்பு பூச்சு.\n3. பல்வேறு பொருட்களின் மிக்க வகை.\n4. தீமை கொண்ட அலங்காரத்திற்கு சிறந்தது.',
      'earthenPotDetails': '1. இயற்கை, கிராமிய வடிவமைப்பு.\n2. உணவை குளிர்ச்சியாக வைத்திருக்கும்.\n3. நீடித்த மற்றும் பாரம்பரியமானது.\n4. சுற்றுச்சூழலுக்கு இடர்பாடு இல்லாதது.',
      'waterPotDetails': '1. நீரை குளிர்ச்சியாக வைத்திருக்கும்.\n2. நிலத்தடி சுவை.\n3. சுற்றுச்சூழலுக்கு இடர்பாடு இல்லாதது.\n4. கிராமிய வடிவமைப்பு.',
      'terracottaPotDetails': '1. மூச்சுக்கான இயற்கை பொருள்.\n2. செடிகளுக்கு சிறந்த நீர் கழிவு.\n3. கிராமிய, திறந்த முடிவு.\n4. வெளி பயன்பாட்டுக்கு சிறந்தது.',
      'herbPotDetails': '1. சிறிய செடிகளுக்கான கூரையான வடிவம்.\n2. நீர் கழிவு отверстிகள் உள்ளன.\n3. பால்கனிகள் சிறந்தவை.\n4. சுற்றுச்சூழலுக்கு இடர்பாடு இல்லாத பொருட்கள்.',
      'glazedPotDetails': '1. மின்னும், பிரகாசமான தோற்றம்.\n2. நீர் முறைப்புகளைத் தவிர்க்கும் மேலமைப்பு.\n3. சுத்தம் செய்ய எளிது.\n4. நீடித்த மற்றும் அலங்காரமானது.',
      'cactusPotDetails': '1. சிறியது, குறைந்த நீர் பயன்படுத்தல்.\n2. நீர் கழிவு உள்ளது.\n3. நவீன வடிவமைப்பு.\n4. அலமரிகளில் இடுகையிடுகிறது.',
      'decorativePotDetails': '1. அழகிய, வினாடிப் பிரசார வடிவங்கள்.\n2. பல்வேறு பொருட்கள்.\n3. சிறந்த அலங்காரம் அல்லது பரிசு.\n4. எந்தவொரு வடிவமைப்பையும் மேம்படுத்துகிறது.',
      'succulentPotDetails': '1. சிறிய, பற்கள் வடிவமைப்பு.\n2. பராமரிப்பு எளிது.\n3. வண்ணங்களில் கிடைக்கும்.\n4. பிஸி உரிமையாளர்களுக்கான சிறந்தது.',
      'vintagePotDetails': '1. பழமைவான, கிராமிய கவர்ச்சி.\n2. பழைய பொருட்களில் உருவாக்கப்பட்டது.\n3. அலங்காரம் அல்லது சேகரிப்புக்கு சிறந்தது.\n4. பாரம்பரிய வடிவமைப்புகளில் பொருந்தும்.',

      'Enable Dark Mode':'டார்க் பயன்முறையை இயக்கு',
      'Dark Mode': 'டார்க் மோட்',

    },
    'te_IN': {
      'Home': 'హోమ్',
      'Search for pottery...': 'మట్టి పాత్ర కోసం శోధించండి...',
      'Pottery App': 'మట్టి పాత్ర యాప్',
      'Notifications': 'నోటిఫికేషన్లు',
      'Buy': 'కొనండి',
      'Settings': 'సెట్టింగ్స్',
      'Logout': 'లాగ్ అవుట్',
      'Menu': 'మెను',
      'Welcome to Pottery Shop': 'మట్టి వస్తువుల అంగడికి స్వాగతం',
      'Select Language': 'భాషను ఎంచుకోండి',
      'English': 'ఇంగ్లీష్',
      'Kannada': 'కన్నడ',
      'Hindi': 'హిందీ',
      'Tamil': 'తమిళ',
      'Telugu': 'తెలుగు',
      'Clay Pot': 'మట్టి పాత్ర',
      'Flower Pot': 'పూల పాత్ర',
      'Color Pot': 'రంగు పాత్ర',
      'Earthen Fine Pot': 'మట్టి ఫైన్ పాత్ర',
      'Water Pot': 'నీటి పాత్ర',
      'Terracotta Pot': 'టెర్రాకోటా పాత్ర',
      'Herb Pot': 'హర్బ్ పాత్ర',
      'Glazed Pot': 'గ్లాజ్డ్ పాత్ర',
      'Cactus Pot': 'కాక్టస్ పాత్ర',
      'Decorative Pot': 'ఆలంకార పాత్ర',
      'Succulent Pot': 'సక్సులెంట్ పాత్ర',
      'Vintage Pot': 'వింటేజ్ పాత్ర',


      'Notifications': 'సూచనలు',
      'New Product Arrival!': 'క్రొత్త ఉత్పత్తి వచ్చింది!',
      'Check out our new pottery collection.': 'మా కొత్త మట్టి కళాఖండాన్ని చూడండి.',
      'New products.': 'కొత్త ఉత్పత్తులు.',
      'Hiking Pot': 'హైకింగ్ పాత్ర',
      'Hiking Pot Details:': 'హైకింగ్ పాత్ర వివరాలు:',
      '1. Lightweight and Compact: Made from lightweight materials like aluminum or titanium, making it easy to carry.':
      '1. తేలికపాటి మరియు కాంపాక్ట్: అల్యూమినియం లేదా టైటానియం వంటి తేలికపాటి పదార్థాలతో తయారు చేయబడింది, వహించడానికి సులభం.',
      '2. Durable and Heat-Resistant: Withstands high heat and rugged conditions for outdoor use.':
      '2. దీర్ఘకాలిక మరియు వేడి నిరోధకత: బహిరంగ ఉపయోగం కోసం అధిక వేడి మరియు కఠిన పరిస్థితులను తట్టుకోగలదు.',
      '3. Efficient Heat Distribution: Conducts heat well, reducing fuel use.':
      '3. సమర్థవంతమైన వేడి పంపిణీ: వేడిని బాగా ప్రసారం చేస్తుంది, ఇంధనం వినియోగాన్ని తగ్గిస్తుంది.',
      '4. Multi-Functional Design: Includes features like foldable handles, strainer lids, and measurement markings.':
      '4. బహుళ-ఫంక్షనల్ డిజైన్: మడతపెట్టగల హ్యాండిల్స్, స్ట్రైనర్ లిడ్స్ మరియు కొలతల గుర్తులు వంటి లక్షణాలను కలిగి ఉంటుంది.',
      '5. Easy to Clean: Often non-stick, making it convenient for minimal-waste camping.':
      '5. శుభ్రం చేయడం సులభం: తరచూ అంటుకోని, తక్కువ వ్యర్థాలు కలిగిన క్యాంపింగ్‌కు అనువుగా ఉంటుంది.',


      'buy_pottery': 'మట్టి వస్తువులు కొనండి',
      'checkout': 'చెకౌట్',
      'added_to_cart': 'మీ కార్టులో జోడించబడింది!',
      'removed_from_cart': 'మీ కార్టు నుండి తొలగించబడింది!',
      'cart_empty': 'మీ కార్టు ఖాళీగా ఉంది!',
      'proceed_to_checkout': 'చెకౌట్ కి వెళ్ళండి',
      'items_in_cart': 'కార్టులో వస్తువులు:',
      'place_order': 'ఆర్డర్ చేయండి',
      'order_placed': 'ఆర్డర్ విజయవంతంగా పెట్టబడింది!',
      'clay_pot': 'మట్టి గిన్నె',
      'flower_pot': 'పువ్వుల గిన్నె',
      'color_pot': 'రంగు గిన్నె',
      'earthen_fine_pot': 'మట్టి సున్నితమైన గిన్నె',
      'water_pot': 'నీటి గిన్నె',
      'terracotta_pot': 'టెర్రాకోటా గిన్నె',
      'herb_pot': 'జరుడు గిన్నె',
      'glazed_pot': 'గ్లేజ్ గిన్నె',
      'cactus_pot': 'కాక్టస్ గిన్నె',
      'decorative_pot': 'అలంకార గిన్నె',
      'succulent_pot': 'సక్క్యులెంట్ గిన్నె',
      'vintage_pot': 'వింటేజ్ గిన్నె',


      'settings': 'సెట్టింగులు',
      'account_settings': 'ఖాతా సెట్టింగులు',
      'dark_mode': 'డార్క్ మోడ్',
      'account_management': 'ఖాతా నిర్వహణ',
      'help_support': 'సహాయం మరియు మద్దతు',


      'account_management': 'ఖాతా నిర్వహణ',
      'manage_account_security': 'మీ ఖాతా భద్రతా సెట్టింగ్‌లను నిర్వహించండి.',
      'change_password': 'పాస్వర్డ్ మార్చండి',
      'enable_2fa': '2-ఫాక్టర్ ప్రామాణీకరణను ఎనేబుల్ చేయండి',
      'enable_2fa_prompt': 'మీరు 2FAని ఎనేబుల్ చేయాలనుకుంటున్నారా?',
      'cancel': 'రద్దు చేయి',
      'enable': 'ఎనేబుల్ చేయండి',
      'change_mobile_number': 'మొబైల్ నంబర్ మార్చండి',
      'enter_new_mobile_number': 'మీ కొత్త మొబైల్ నంబర్‌ను క్రింద ఇవ్వండి:',
      'new_mobile_number': 'కొత్త మొబైల్ నంబర్',
      'mobile_number_changed': 'మొబైల్ నంబర్ విజయవంతంగా మార్చబడింది',
      'help_support': 'సహాయం & మద్దతు',
      'welcome_help_support': 'సహాయం & మద్దతు లోకి స్వాగతం!',
      'find_answers_help_support': 'సాధారణ ప్రశ్నలకు సమాధానాలను కనుగొనండి లేదా మద్దతుతో సంప్రదించండి.',
      'help_articles': 'సహాయం వ్యాసాలు',
      'contact_support': 'మద్దతును సంప్రదించండి',
      'support_numbers': 'మీరు ఈ క్రింది నంబర్లతో మద్దతును సంప్రదించవచ్చు:\n1. 6379453853\n2. 9943790029',
      'opening_general_support': 'సాధారణ మద్దతు వివరాలను తెరవడం',
      'open_support_details': 'మద్దతు వివరాలను తెరవండి',
      'contacting_support': 'మద్దతును సంప్రదిస్తున్నారు',

      'account_settings': 'ఖాతా సెట్టింగ్స్',
      'manage_account_info': 'ఇక్కడ మీ ఖాతా సెట్టింగ్‌లను నిర్వహించండి.',
      'update_account_info': 'ఖాతా సమాచారం అప్‌డేట్ చేయండి',
      'new_account_info': 'కొత్త ఖాతా సమాచారం',
      'cancel': 'రద్దు చేయి',
      'save': 'సేవ్ చేయి',



      'sellersPageTitle': 'విక్రేత పేజీ',
      'manageProducts': 'ఉత్పత్తులను నిర్వహించండి',
      'addNewPot': 'కోసం కొత్త కుండి జోడించండి',
      'enterPotName': 'కుండి పేరు నమోదు చేయండి',
      'cancel': 'రద్దు',
      'add': 'చేర్చండి',
      'editProduct': 'ఉత్పత్తి సవరించు',
      'productDetails': 'ఉత్పత్తి వివరాలు',
      'save': 'సేవ్ చేయండి',
      'addNewPotButton': 'కొత్త కుండి జోడించండి',
      'Select Language': 'భాషను ఎంచుకోండి',


      'Account': 'ఖాతా',
      'Profile Information': 'ప్రొఫైల్ సమాచారం',
      'Full Name': 'పూర్తి పేరు',
      'Email': 'ఈమెయిల్',
      'Business Information': 'వ్యాపార సమాచారం',
      'Business Name': 'వ్యాపార పేరు',
      'Business Contact': 'వ్యాపార సంప్రదింపు',
      'Change Password': 'పాస్వర్డ్ మార్చు',
      'New Password': 'కొత్త పాస్వర్డ్',
      'Save Changes': 'మార్పులను సేవ్ చేయండి',
      'Success': 'విజయం',
      'Account details updated successfully.': 'ఖాతా వివరాలు విజయవంతంగా నవీకరించబడినవి.',


      'helpSupportTitle': 'సహాయం మరియు మద్దతు',
      'resetPassword': 'మీ పాస్వర్డ్‌ను రీసెట్ చేయడం ఎలా',
      'resetPasswordContent': 'మీ పాస్వర్డ్‌ను రీసెట్ చేయడానికి, సెట్టింగ్‌ల పేజీకి వెళ్లి "పాస్‌వర్డ్ మార్చండి"ను ఎంచుకోండి. కొత్త పాస్‌వర్డ్ సృష్టించడానికి సూచనలను అనుసరించండి.',
      'enable2FA': '2FAని ఎలా ప్రారంభించాలి',
      'enable2FAContent': 'రెండు-సంఖ్యల ధృవీకరణను ప్రారంభించడానికి, భద్రతా సెట్టింగ్‌లలోకి వెళ్లి 2FAని ప్రారంభించండి. మీ ఖాతాను భద్రత చేయడానికి సూచనలను అనుసరించండి.',
      'contactSupport': 'సపోర్ట్‌ను ఎలా సంప్రదించాలి',
      'contactSupportContent': 'సపోర్ట్ కోసం, మా వెబ్‌సైట్‌లో "మమ్మల్ని సంప్రదించండి" ఫారమ్ ద్వారా లేదా మా హెల్ప్‌లైన్‌కు కాల్ చేయండి: 123-456-7890.',
      'FAQ': 'తరచుగా అడిగే ప్రశ్నలు',
      'FAQContent': 'ఇక్కడ కొన్ని సాధారణ ప్రశ్నలకు సమాధానాలు ఉన్నాయి. మరింత సమాచారం కోసం సపోర్ట్‌ను సంప్రదించండి.',
      'termsConditions': 'నియమాలు మరియు షరతులు',
      'termsConditionsContent': 'మా సేవను ఉపయోగించడం ద్వారా, మీరు మా నియమాలు మరియు షరతులను పాటించడానికి అంగీకరిస్తారు. మరింత సమాచారం కోసం మా వెబ్‌సైట్ చూడండి.',
      'privacyPolicy': 'గోప్యతా విధానం',
      'privacyPolicyContent': 'మీ గోప్యతను మేము గౌరవిస్తున్నాము. మా గోప్యతా విధానాన్ని చదవండి.',


      'clayPot': 'మట్టి గోడం',
      'flowerPot': 'పువ్వుల గోడం',
      'colorPot': 'రంగు గోడం',
      'earthenPot': 'మట్టి గోడం',
      'waterPot': 'నీరు గోడం',
      'terracottaPot': 'టెర్రకోటా గోడం',
      'herbPot': 'సమిష్టి గోడం',
      'glazedPot': 'గ్లాజ్ గోడం',
      'cactusPot': 'కాక్టస్ గోడం',
      'decorativePot': 'అలంకార గోడం',
      'succulentPot': 'సక్సులెంట్ గోడం',
      'vintagePot': 'పాతకాలపు గోడం',

      'clayPotDetails': '1. ప్రకృతిసిద్ధమైన మట్టితో తయారు చేయబడింది.\n2. మెల్లగా వండటానికి అనుకూలం.\n3. పర్యావరణ స్నేహపూర్వకం.\n4. వేడి మరియు తేమను నిలుపుకుంటుంది.',
      'flowerPotDetails': '1. అలంకార మరియు బహు-ఉపయోగం.\n2. నీరు పారిపోయే అవకాశాలు ఉన్నాయి.\n3. అనుకూల పరిమాణాలు.\n4. తేలికపాటి మరియు పోర్టబుల్.',
      'colorPotDetails': '1. జీవితం మరియు అనుకూలంగా మార్చుకోవచ్చు.\n2. యూ.వి. రక్షణతో కవచాలు.\n3. అనేక రకాల పదార్థాలు.\n4. థీమ్ అలంకరణకు అనుకూలం.',
      'earthenPotDetails': '1. ప్రకృతి, గ్రామీణ డిజైన్.\n2. ఆహారాన్ని చల్లగా ఉంచుతుంది.\n3. టిక్కెడు మరియు సాంప్రదాయికం.\n4. పర్యావరణ స్నేహపూర్వకం.',
      'waterPotDetails': '1. నీరును చల్లగా ఉంచుతుంది.\n2. భూమి రుచి.\n3. పర్యావరణ స్నేహపూర్వకం.\n4. గ్రామీణ డిజైన్.',
      'terracottaPotDetails': '1. శ్వాస తీసుకునే ప్రకృతి పదార్థం.\n2. మొక్కల కోసం అనుకూలమైన నీటి పారుదల.\n3. గ్రామీణ, మూసుకోని ముగింపు.\n4. బయట ఉపయోగానికి గొప్పది.',
      'herbPotDetails': '1. చిన్న మూలికల కోసం కంపాక్ట్.\n2. నీటి పారుదల రంధ్రాలు ఉన్నాయి.\n3. బాల్కనీలకు అనుకూలం.\n4. పర్యావరణ స్నేహపూర్వక పదార్థాలు.',
      'glazedPotDetails': '1. గ్లోస్సీ, జీవిత పరిపూర్ణత.\n2. శోషణ రహిత ఉపరితలము.\n3. శుభ్రం చేయడం సులభం.\n4. టిక్కెడు మరియు అలంకారమైనది.',
      'cactusPotDetails': '1. చిన్నది, కనీస నీటి వినియోగం.\n2. నీటి పారుదల ఉంటుంది.\n3. ఆధునిక డిజైన్.\n4. అలమారీలకు అనుకూలం.',
      'decorativePotDetails': '1. శైలిని అందించే, సంక్లిష్టమైన డిజైన్లు.\n2. బహుళ పదార్థాల ఎంపిక.\n3. అలంకారం లేదా కానుకకు అనుకూలం.\n4. ఎలాంటి శైలినీ మెరుగుపరుస్తుంది.',
      'succulentPotDetails': '1. కంపాక్ట్, అంగుళం వెడల్పు డిజైన్.\n2. సులభమైన నిర్వహణ.\n3. రంగులలో అందుబాటులో ఉంటుంది.\n4. బిజీ యజమానుల కోసం గొప్పది.',
      'vintagePotDetails': '1. పాతకాలపు, గ్రామీణ ఆకర్షణ.\n2. పాత పదార్థాలతో రూపొందించబడింది.\n3. అలంకారం లేదా సేకరణకు గొప్పది.\n4. క్లాసిక్ థీమ్‌లకు సరిపోతుంది.',
      'Enable Dark Mode': 'డార్క్ మోడ్‌ని ప్రారంభించు',

      'Dark Mode': 'డార్క్ మోడ్',

    },
  };
}
*/